version: '3.9'

volumes:
    mongodb_volume:

services:
    mongodb:
        container_name: mongodb
        image: mongo:latest
        volumes:
            - ./db/mongo/init_database.js:/docker-entrypoint-initdb.d/init_database.js
            - mongodb_volume:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
            - MONGO_INITDB_DATABASE=cryptomonitor
        restart: always
            
    app:
        container_name: cryptomonitor_web
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            - ConnectionStrings__MongoDb=mongodb://admin:admin@mongodb/cryptomonitor
            - SchedulerOptions__Jobs__0__Cron=0 0/1 * 1/1 * ? *
        restart: always
        ports:
            - 18080:80
        depends_on:
            - mongodb